# https://docs.travis-ci.com/user/languages/android
language: android
jdk: oraclejdk8
# Container builds don't have enough memory to reliably finish without being
# killed, so pretend sudo is required so we don't use the container infra.
# See: https://github.com/travis-ci/travis-ci/issues/5582
sudo: required
android:
    components:
        - tools
        - platform-tools
        - build-tools-25.0.2
        - android-25
        - extra-android-m2repository
        - extra-google-m2repository

# "avoid uploading the cache after every build"
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

script: ./gradlew jobdispatcher:build testapp:assemble
